version: "3.9"
services:
  config-server:
    container_name: config-server
    image: config-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - application-network

networks:
  application-network:
    external: true